#version: "3.8"
#
#services:
#  mysqldb:
#    container_name: mysqldb
#    image: mysql
#    ports:
#      - '3366:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: bsmartdb
#
#  springboot-restful-bsmart:
#    container_name: bsmart-app
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysqldb

version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
#    expose:
#      - 3306
  app-bsmart:
    depends_on:
      - mysqldb
    build:
      context: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
