package fpt.project.bsmart.director;

public class NotificationConstant {
    public final static String COURSE_APPROVAL_TITLE = "COURSE_APPROVAL_TITLE";
    public final static String COURSE_APPROVAL_CONTENT = "COURSE_APPROVAL_CONTENT";
    public final static String TRANSACTION_PAYMENT_TITLE = "TRANSACTION_PAYMENT_TITLE";
    public final static String TRANSACTION_PAYMENT_CONTENT = "TRANSACTION_PAYMENT_CONTENT";
    public final static String COURSE_APPROVAL_PROFILE_TITLE = "COURSE_APPROVAL_PROFILE_TITLE";
    public final static String COURSE_APPROVAL_PROFILE_CONTENT = "COURSE_APPROVAL_PROFILE_CONTENT";
    public final static String CLASS_ENROLL_SUCCESS_TITLE = "CLASS_ENROLL_SUCCESS_TITLE";
    public final static String CLASS_ENROLL_SUCCESS_CONTENT = "CLASS_ENROLL_SUCCESS_CONTENT";
    public final static String CLASS_APPROVAL_TITLE = "CLASS_APPROVAL_TITLE";
    public final static String CLASS_APPROVAL_CONTENT = "CLASS_APPROVAL_CONTENT";
    public final static String ACCOUNT_REGISTER_SUCCESSFUL_TITLE = "ACCOUNT_REGISTER_SUCCESSFUL_TITLE";
    public final static String ACCOUNT_REGISTER_SUCCESSFUL_CONTENT = "ACCOUNT_REGISTER_SUCCESSFUL_CONTENT";


}
