server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
 #------------------DB --------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.173.155.221:3307/bsmartdb
#    url: jdbc:mysql://localhost:3306/bsmartdb
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    generate-ddl: true
  #------------------MinIO --------------#
minio:
  access:
    key: Ed9hULk92IyS2Glb
    secret: GVk3tHgV3x6tiCR158V0RyFxOFH5IM5O
  url: http://103.173.155.221:9000
  bucket:
    name: bsmart
  endpoint: http://103.173.155.221:9000
  #------------------ -------------------#


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/vuondau-application
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2KB
      max-file-size: 5MB
# Keycloak settings
#keycloak:
#  realm: vuondau-application
#  resource: springboot-admin-client
#  app-client: vuondau
#  auth-server-url: http://vuondau-keycloak.amazingtech.vn/auth
#  credentials:
#    secret: 0Z8fWR17uURSeTWmKd4EdapEUF8ck9ku





