server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/bsmartdb
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://103.173.155.221:8088/auth/realms/Bsmart
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2KB
      max-file-size: 5MB


# Keycloak settings
keycloak:
  realm: bsmart
  resource: springboot-admin-client
  app-client: bsmart
  auth-server-url: http://keycloak:8080/auth
  credentials:
    secret: 56ce136b-1dc5-40cb-8a2f-dfb97005a3ef
#------------------Security Specific Properties-------
app:
  secret-key: J@!gt*K

beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000


logging:
  file:
    path: /logs
    name: /logs/application.log

vnp_Returnurl: http://103.173.155.221:8080/api/transactions/pay/vnpay/result



