server:
  port: 8082
  forward-headers-strategy: framework
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/temp
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 20MB
      file-size-threshold: 2KB
      max-file-size: 20MB
#------------------Security Specific Properties-------
app:
  secret-key: J@!gt*K
  oauth2-redirect: https://mismart.vercel.app/login-success
beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000


logging:
  file:
    path: /logs
    name: /logs/application.log

vnp_Returnurl: http://103.173.155.221:8080/api/transactions/pay/vnpay/result



