server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 874513160878-adut1nl0uallr5jfbr9hm3fapu7oqkgc.apps.googleusercontent.com
            clientSecret: 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
  config:
    import: optional:file:.env[.properties]
  messages:
    always-use-message-format: false
    basename: i18n/messages_vi
    encoding: UTF-8
    use-code-as-default-message: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: thanhhuyne113@gmail.com
    password: aktumoajjptyhfjn
    port: '587'
moodle:
  url:
    base: http://moodle-vuondau.amazingtech.vn/webservice/restful/server.php/
    course:
      get: core_course_get_courses
      create: core_course_create_courses
      delete: core_course_delete_courses
      content:
        get: core_course_get_contents
      member:
        enrol: enrol_manual_enrol_users
        unenrol: enrol_manual_unenrol_users
      grade:
        get: gradereport_user_get_grade_items
    resource:
      get: core_course_get_contents
    category:
      get: core_course_get_categories
      create: core_course_create_categories
    role:
      get: local_wsgetroles_get_roles
    user:
      get: core_user_get_users_by_field
    assignments:
      get: mod_assign_get_submissions
    root: http://moodle-vuondau.amazingtech.vn
  token: c60c932ed4585b4534362b56045e653d

app:
  firebase-configuration-file: /store/vuondau-450bf-firebase-adminsdk-al83z-5d94e1225d.json
  secret-key: J@!gt*K
  oauth2:
    authorizedRedirectUris: http://localhost:8081/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect,http://localhost:3000/login,http://localhost:3000/login

# Return URL after payment
payment-redirect: http://localhost:10000/processing
teaching-confirmation-url: localhost:15212/
moodle-course-url: http://moodle-vuondau.amazingtech.vn/course/view.php?id=

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# VNPay Config
vnp_product_type: 250000
vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_HashSecret: NJJDAQCFVUBSYMOUNBJUZJQSXDEWEPKY
vnp_Returnurl: http://localhost:8082/api/transactions/pay/vnpay/result
vnp_TmnCode: 2P0JI5DH
vnp_apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/merchant.html

# External API
provinces: https://provinces.open-api.vn/api/?depth=1

# Mail Config
mail:
  properties:
    mail:
      smtp:
        starttls:
          enable: 'true'
        auth: 'true'
  host: smtp.gmail.com
  username: thanhhuyne113@gmail.com
  password: xrcnbqqqejhqcmqc
  port: '587'

bank:
  url: https://api.vietqr.io/v2/banks

#------------------Security Specific Properties-------
beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000
  #------------------MinIO DEV---------------#
minio:
  access:
    key: Ed9hULk92IyS2Glb
    secret: GVk3tHgV3x6tiCR158V0RyFxOFH5IM5O
  url: http://103.173.155.221:9000
  bucket:
    name: bsmart
  endpoint: http://103.173.155.221:9000

keycloak:
  realm: bsmart
  resource: springboot-admin-client
  app-client: bsmart
  auth-server-url: http://103.173.155.221:8088/auth
  credentials:
    secret: 56ce136b-1dc5-40cb-8a2f-dfb97005a3ef

icon:
  success: http://103.173.155.221:9000/bsmart/checked.png
  fail: http://103.173.155.221:9000/bsmart/fail.png

activate:
  template:

host:
  url: http://103.173.155.221:3000/confirm_email/





