server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://103.173.255.39:3306/vuondau
=======
    url: jdbc:mysql://localhost:3306/bsmartdb
>>>>>>> 1f025c1628f62d3263107e111e08818aee09fac1
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
<<<<<<< HEAD
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/vuondau-application
=======

>>>>>>> 1f025c1628f62d3263107e111e08818aee09fac1
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2KB
      max-file-size: 5MB
<<<<<<< HEAD


minio:
  bucket: requestformstudent
  url: http://103.173.255.39:9000
  access-key: ELrwUZXIzBLOlp5s
  secret-key: gCHswS6KZKVohYsIiWKCnfvF5UWbBUWE

# Keycloak settings
keycloak:
  realm: vuondau-application
  resource: springboot-admin-client
  app-client: vuondau
  auth-server-url: http://vuondau-keycloak.amazingtech.vn/auth
  credentials:
    secret: 0Z8fWR17uURSeTWmKd4EdapEUF8ck9ku

=======
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

bezkoder:
  app:
    jwtExpirationMs: '86400000'
    jwtSecret: bezKoderSecretKey

>>>>>>> 1f025c1628f62d3263107e111e08818aee09fac1



