server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysqldb:3307/bsmartdb
    url: jdbc:mysql://localhost:3306/bsmartdb
    username: root
    password: admin


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vuondau-keycloak.amazingtech.vn/auth/realms/vuondau-application
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2KB
      max-file-size: 5MB
minio:
  bucket: requestformstudent
  url: http://103.173.255.39:9000
  access-key: ELrwUZXIzBLOlp5s
  secret-key: gCHswS6KZKVohYsIiWKCnfvF5UWbBUWE

# Keycloak settings
keycloak:
  realm: vuondau-application
  resource: springboot-admin-client
  app-client: vuondau
  auth-server-url: http://vuondau-keycloak.amazingtech.vn/auth
  credentials:
    secret: 0Z8fWR17uURSeTWmKd4EdapEUF8ck9ku




#------------------Security Specific Properties-------
app:
  secret-key: J@!gt*K

beholder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000
